-- MySQL Script generated by MySQL Workbench
-- 07/27/14 12:31:55
-- Model: New Model Version: 1.0
SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema mydb1
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb1` DEFAULT CHARACTER SET utf8 COLLATE utf8_general_ci ;
USE `mydb1` ;

-- -----------------------------------------------------
-- Table `mydb1`.`User`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb1`.`User` (
  `UserID` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `UserName` VARCHAR(200) NULL,
  `Email` VARCHAR(200) NULL,
  `DisplayName` VARCHAR(200) NULL,
  `Password` BINARY(64) NULL,
  `CookieID` VARCHAR(200) NULL,
  `Avatar` VARCHAR(255) NULL,
  PRIMARY KEY (`UserID`),
  UNIQUE INDEX `UserID_UNIQUE` (`UserID` ASC),
  UNIQUE INDEX `UserName_UNIQUE` (`UserName` ASC),
  UNIQUE INDEX `CookieID_UNIQUE` (`CookieID` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb1`.`Project`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb1`.`Project` (
  `ProjectID` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `Title` VARCHAR(200) NULL,
  `Description` VARCHAR(200) NULL,
  `StartDate` DATE NULL,
  `TargetDate` DATE NULL,
  `ManagerID` INT UNSIGNED NOT NULL,
  `Status` ENUM('Started','Not Started','Finished','In Progress') NULL DEFAULT 'Not Started',
  `Icon` VARCHAR(255) NULL,
  `ImageURL` VARCHAR(255) NULL,
  PRIMARY KEY (`ProjectID`),
  UNIQUE INDEX `ProjectID_UNIQUE` (`ProjectID` ASC),
  INDEX `ManagerID_idx` (`ManagerID` ASC),
  CONSTRAINT `ManagerID`
    FOREIGN KEY (`ManagerID`)
    REFERENCES `mydb1`.`User` (`UserID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;
CREATE TRIGGER `delproject` AFTER DELETE ON `Project`
	FOR EACH ROW
		DELETE FROM `ProjectTask` WHERE ProjectID = OLD.ProjectID;

-- -----------------------------------------------------
-- Table `mydb1`.`ProjectUser`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb1`.`ProjectUser` (
  `UserID` INT UNSIGNED NULL,
  `ProjectID` INT UNSIGNED NULL,
  INDEX `ProjectID_idx1` (`ProjectID` ASC),
  INDEX `UserID_idx1` (`UserID` ASC),
  CONSTRAINT `UserID`
    FOREIGN KEY (`UserID`)
    REFERENCES `mydb1`.`User` (`UserID`)
    ON DELETE CASCADE
    ON UPDATE NO ACTION,
  CONSTRAINT `ProjectID`
    FOREIGN KEY (`ProjectID`)
    REFERENCES `mydb1`.`Project` (`ProjectID`)
    ON DELETE CASCADE
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb1`.`Task`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb1`.`Task` (
  `TaskID` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `Priority` ENUM('Low','Normal','High','Urgent') NULL DEFAULT 'Normal',
  `HasDependency` TINYINT(1) NULL,
  `Deadline` TIMESTAMP NULL,
  `Title` VARCHAR(200) NULL,
  `Notes` VARCHAR(200) NULL,
  `Description` VARCHAR(200) NULL,
  `Scope` VARCHAR(200) NULL,
  `Status` ENUM('Backlog','Started','In Progress','Testing','Peer Review','Complete') NULL,
  PRIMARY KEY (`TaskID`),
  UNIQUE INDEX `TaskID_UNIQUE` (`TaskID` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb1`.`ProjectTask`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb1`.`ProjectTask` (
  `ProjectID` INT UNSIGNED NULL,
  `TaskID` INT UNSIGNED NULL,
  INDEX `ProjectID_idx3` (`ProjectID` ASC),
  INDEX `TaskID_idx3` (`TaskID` ASC),  
CONSTRAINT `ProjectID2`
    FOREIGN KEY (`ProjectID`)
    REFERENCES `mydb1`.`Project` (`ProjectID`)
    ON DELETE CASCADE
    ON UPDATE NO ACTION,
  CONSTRAINT `TaskID`
    FOREIGN KEY (`TaskID`)
    REFERENCES `mydb1`.`Task` (`TaskID`)
    ON DELETE CASCADE
    ON UPDATE NO ACTION)  
ENGINE = InnoDB;

CREATE TRIGGER `deltask` AFTER DELETE ON `ProjectTask`
	FOR EACH ROW
		DELETE FROM `Task` WHERE TaskID = OLD.TaskID;

-- -----------------------------------------------------
-- Table `mydb1`.`UserTask`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb1`.`UserTask` (
  `UserID` INT UNSIGNED NULL,
  `TaskID` INT UNSIGNED NULL,
  INDEX `UserID_idx2` (`UserID` ASC),
  INDEX `TaskID_idx2` (`TaskID` ASC),
  CONSTRAINT `UserID2`
    FOREIGN KEY (`UserID`)
    REFERENCES `mydb1`.`User` (`UserID`)
    ON DELETE CASCADE
    ON UPDATE NO ACTION,
  CONSTRAINT `TaskID2`
    FOREIGN KEY (`TaskID`)
    REFERENCES `mydb1`.`Task` (`TaskID`)
    ON DELETE CASCADE
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb1`.`Log`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb1`.`Log` (
  `LogID` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `RemoteAddr` VARCHAR(255) NULL,
  `RemoteHost` VARCHAR(255) NULL,
  `RemotePort` SMALLINT NULL,
  `ServletPath` VARCHAR(255) NULL,
  `RequestType` VARCHAR(255) NULL,
  `RequestCookie` VARCHAR(255) NULL,
  `RequestTime` TIMESTAMP NULL,
  PRIMARY KEY (`LogID`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb1`.`TaskDependencies`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb1`.`TaskDependencies` (
  `TaskID` INT UNSIGNED NULL,
  `DependentTask` INT UNSIGNED NULL,
  INDEX `TaskID_idx` (`TaskID` ASC),
  INDEX `DependentTask_idx` (`DependentTask` ASC),
  CONSTRAINT `TaskID3`
    FOREIGN KEY (`TaskID`)
    REFERENCES `mydb1`.`Task` (`TaskID`)
    ON DELETE CASCADE
    ON UPDATE NO ACTION,
  CONSTRAINT `DependentTask`
    FOREIGN KEY (`DependentTask`)
    REFERENCES `mydb1`.`Task` (`TaskID`)
    ON DELETE CASCADE
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
